# Generated by Django 3.2.7 on 2021-11-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211101_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tessiu',
            name='inflammation',
            field=models.FloatField(verbose_name='inflamación'),
        ),
    ]
