# Generated by Django 3.2.7 on 2021-11-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_distance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distance',
        ),
    ]
