# Generated by Django 3.2.7 on 2021-11-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grafo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distance',
        ),
    ]
